### ISSUE TITLE
Refatoração e compatibilidade com givewp 3.0.0

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/payment-erede-for-givewp#5]
- [x] Configurar sistema de autoloader com composer;
- [x] Adição de compatibilidade com template GiveWP 3.0.0;
- [x] Adição de limpeza de logs automática utilizando WP-CRON;
- [x] Otimizar código e retirar redundâncias;
- [x] Escapar atributos que são mostrados ao usuário;
- [x] Sanitizar todos os atributos salvos do formulário.

**Comment by helonfranca02** [comment]
Concluído!
